# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-gAHlrY7vyxofO4g_jFLYYIE6pv7qpg
"""

pip install dash plotly pandas

import pandas as pd
import plotly.express as px
import dash
from dash import dcc, html

# Sample dataset for European countries
data = {
    "country": [
        "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus",
        "Czech Republic", "Denmark", "Estonia", "Finland", "France",
        "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia",
        "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland",
        "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden", "United Kingdom"
    ],
    "iso_alpha": [
        "AUT", "BEL", "BGR", "HRV", "CYP", "CZE", "DNK", "EST", "FIN", "FRA",
        "DEU", "GRC", "HUN", "IRL", "ITA", "LVA", "LTU", "LUX", "MLT", "NLD",
        "POL", "PRT", "ROU", "SVK", "SVN", "ESP", "SWE", "GBR"
    ],
    "gdp_ppp": [
        55000, 48000, 15000, 25000, 35000, 32000, 60000, 25000, 52000, 45000,
        50000, 28000, 23000, 80000, 40000, 20000, 22000, 120000, 30000, 53000,
        28000, 26000, 18000, 25000, 30000, 34000, 58000, 45000
    ]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Define GDP brackets with a $5,000 range
def get_gdp_bracket(value):
    lower_bound = (value // 5000) * 5000
    upper_bound = lower_bound + 5000
    return f"${lower_bound} - ${upper_bound}"

df['gdp_bracket'] = df['gdp_ppp'].apply(get_gdp_bracket)

# Create a choropleth map using Plotly Express
fig = px.choropleth(
    df,
    locations="iso_alpha",       # ISO country codes for mapping
    color="gdp_bracket",         # Colors based on the GDP bracket
    hover_name="country",        # Display the country name on hover
    hover_data={
        "gdp_ppp": True,         # Show exact GDP per capita value
        "gdp_bracket": False,    # Do not show the bracket in the hover info
        "iso_alpha": False       # Remove the ISO code from hover info
    },
    scope="europe",              # Focus the map on Europe
    title="GDP per Capita PPP in Europe",
    labels={"gdp_ppp": "GDP per Capita (PPP)"}
)

# Update the layout to enlarge the figure
fig.update_layout(height=800, width=1200)

# Set up the Dash app
app = dash.Dash(__name__)

app.layout = html.Div(children=[
    html.H1(children='GDP per Capita PPP Dashboard'),
    html.Div(children='Interactive map of GDP per Capita PPP in Europe.'),
    dcc.Graph(
        id='gdp-map',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)